version: '3.8'

services:
  mysql:
    image: mysql:latest
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: cocovoit
      MYSQL_DATABASE: cocovoit
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      MYSQL_ROOT_PASSWORD: cocovoit
    ports:
      - "8080:80"
    depends_on:
      - mysql

  restapi:
    build:
      context: ./CocovoitAPI/CocovoitAPI
      dockerfile: Dockerfile
    container_name: cocovoit_restapi
    ports:
      - "44318:80"
      - "9100:9100"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - LOKI_URL=http://loki:3100
    depends_on:
      - mysql
    volumes:
      - logs:/var/log/cocovoit

volumes:
  mysql_data:
  logs:
